Repository boostcampaitech5/level3_recsys_finalproject-recsys-08, pull requests merged in 2023-08, with the labels that each got.

#12 [Feat] scrap listed enterprises sector and theme
  naver_financial_crawling.ipynb
Labels: 📄 Data

#15 [Feat] Collect Preprocess data
  enterprise_valuation/company_data_check.ipynb
  enterprise_valuation/smes_data_scrapping.ipynb
Labels: 📄 Data

#18 [Feat] Feat 1/business embedding/summarization
  summarization/dataset.py
  summarization/finetune.py
  summarization/get_model_binary.py
  summarization/summarization.ipynb
Labels: 💎 Model

#22 [Feat] Feat 9/top k recommendation/sasrec/train
  sasrec_train.ipynb
  top_k_recommendation/sasrec_train.ipynb
Labels: enhancement

#20 [Feat] Add ANNOY Model
  top_k_recommendation/model/annoy.py
Labels: 💎 Model

#25 [Feat] Collect DART & SMES data
  top_k_recommendation/data/cash.py
  top_k_recommendation/data/crawling.py
  top_k_recommendation/data/crawling_jemu.py
  top_k_recommendation/data/dart_preprocessing.py
  top_k_recommendation/data/interaction_preprocessing.py
  top_k_recommendation/data/mainmatter_interaction.py
  top_k_recommendation/data/smes_balance_sheet.py
  top_k_recommendation/data/smes_income_statement.py
Labels: 📄 Data

#21 [Feat] Add retrieval jupyter notebook
  retrieval/retrieval.ipynb
Labels: 💎 Model

#16 [Feat] Enterprise Valuation using DCF
  enterprise_valuation/DCF.ipynb
Labels: 💎 Model

#14 [Feat] Measure predicted enterprise value
  value_testing.ipynb
Labels: enhancement
